version: '3.8'

services:
  db_redis:
    image: "redis:6.2-alpine"
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --loglevel warning
    volumes:
      - cache:/data
    networks:
      - beers_network

  db_beers:
    container_name: db_beers
    image: "postgres:13"
    volumes :
      - pgdata:/var/lib/postgresql/data
    restart: always
    env_file:
      - .env.beers
    ports:
      - "9001:9001"
    networks:
      - beers_network
    command: -p 9001
    depends_on:
      - db_redis

  beers_backend:
    build:
      dockerfile: dockerfile.backend-beers
      context: .
    ports:
      - 8082:8082
    volumes:
      - .:/test_ms_beer/beers_app
    env_file:
      - .env.beers
    depends_on:
      - db_beers
    networks:
      - beers_network

networks:
  beers_network:
    driver: bridge

volumes:
    pgdata:
    cache:
      driver: local
