FROM golang:1.17-alpine

RUN apk add --update git

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN CGO_ENABLED=0 go build -o /usr/local/bin/beers_app
CMD [ "/usr/local/bin/beers_app" ]